# Generated by Django 5.2.8 on 2025-11-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default='2000-01-01T10:00:00', verbose_name='Дедлайн'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default='True', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
