# Generated by Django 5.2.8 on 2025-11-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_deadline_task_status_alter_task_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='Учеба', verbose_name='Статус'),
        ),
    ]
