# Generated by Django 5.2.8 on 2025-11-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
    ]
