# Generated by Django 5.2.8 on 2025-11-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_task_status_task_user_alter_task_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
