# Generated by Django 5.2.8 on 2025-11-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.CharField(default='admin', verbose_name='Пользователь'),
        ),
    ]
