# Generated by Django 5.2.8 on 2025-11-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
